use Mix.Config

config :bitpal, backends: [BitPal.Backend.Flowee]
config :bitpal, BitPal.ExchangeRate, backends: [BitPal.ExchangeRate.Kraken]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :demo, Demo.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info
