import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :demo, Demo.Endpoint,
  url: [host: "demo.bitpal.dev", port: 443],
  http: [:inet6, port: 4040],
  check_origin: ["https://demo.bitpal.dev/"],
  server: true,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :demo, Demo.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "smtp.fastmail.com",
  ssl: true,
  tls: :if_available,
  auth: :always,
  port: 465,
  retries: 2,
  no_mx_lookups: false
